List
VMenshchikov/fit_os_21212 pull request #2
Opened 2023-12-20 17:25 UTC by VMenshchikov

2023-12-21 14:00 UTC, k-stolyarov requested changes
![image](https://github.com/VMenshchikov/fit_os_21212/assets/1216039/3fea5f36-94c2-4c3d-8cd9-0fefe4e65cd6)

2023-12-21 14:00 UTC, k-stolyarov commented on list/mutex/main.c
> +void* swaper(void* arg) {
In your implementation first generated string is always the same . It is crying and wants to  move somewhere.

2023-12-21 14:00 UTC, k-stolyarov commented on list/mutex/main.c
> +    pthread_mutex_unlock(&nodes[0]->sync);
???!!!

2023-12-21 19:47 UTC, VMenshchikov commented on list/mutex/main.c
> +void* swaper(void* arg) {
вопрос только в однообразности строки?(и еще 2х реализациях?.. я хотел что бы Вы увидели одну, ведь остальные похожи и что бы не пришлось править в трех местах одно и то же)

2023-12-21 20:04 UTC, VMenshchikov commented
убрал непотребство в конце файла, добавил установку семени от времени для генерации разных строк, исправил ошбку в ифе при проверке на нул

2023-12-21 20:27 UTC, VMenshchikov commented on list/mutex/main.c
> +void* swaper(void* arg) {
разумеется после одобрения этого варианта я быстро докину другие синхронизации

2023-12-25 14:00 UTC, k-stolyarov commented on list/mutex/main.c
> +void* swaper(void* arg) {
according to your logic you need to fix it correctly before implemention all others. . It has elegant several-lines solution  or student one )

2023-12-25 14:02 UTC, k-stolyarov commented on list/mutex/main.c
> +            pthread_mutex_lock(&storage->first->sync);
You have race condition here.  Explain where and fix it.

2023-12-25 14:06 UTC, k-stolyarov commented
> убрал непотребство в конце файла, добавил установку семени от времени для генерации разных строк, исправил ошбку в ифе при проверке на нул

extremely ugly but acceptable solution. Awaiting all remaining implementations and comparison between them with explanation of result differences please

2023-12-30 18:43 UTC, VMenshchikov commented
![изображение](https://github.com/VMenshchikov/fit_os_21212/assets/105418201/14eeb228-1caf-4e63-b08f-b287c2dec464)
mutex и spinlock мы обсуждали

rwmutex позволяет блокироваться на чтение нескольким потокам одновременно, а для записи поток должен завладеть ресурсом полностью
из этого следует уменьшение времени в нашей задаче

2024-01-28 05:27 UTC, k-stolyarov approved these changes
Accepted

2024-04-18 17:33 UTC, merged