Proxy
VMenshchikov/fit_os_21212 pull request #3
Opened 2023-12-20 17:25 UTC by VMenshchikov

2023-12-25 13:57 UTC, k-stolyarov requested changes

2023-12-25 13:57 UTC, k-stolyarov commented on proxy/threads.c
> +            soc = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
Please list all possible types of sockets and families. Are all of them available for HTTP communication ?

2023-12-25 13:57 UTC, k-stolyarov commented on proxy/threads.c
> +        for (rp = result; rp != NULL; rp = rp->ai_next) {
what will happen if none address is suitable ?

2023-12-25 13:57 UTC, k-stolyarov commented on proxy/threads.c
> +        start = strstr(buffer, "//");
with knowledge of your code here I can break your proxy and crach your proxy., Explain how and fix it.

2023-12-25 13:57 UTC, k-stolyarov commented on proxy/threads.c
> +        sPollPush(spoll, newSockets);
you mean you return newSockets into poll queue to restart this cycle again  once more ?  I cannot understand logic of your implementation :( Please explain it briefly.

2024-01-04 03:59 UTC, k-stolyarov commented on proxy/threads.c
> +            soc = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
?

2024-01-04 03:59 UTC, k-stolyarov commented on proxy/threads.c
> +        for (rp = result; rp != NULL; rp = rp->ai_next) {
?

2024-01-04 04:02 UTC, k-stolyarov commented on proxy/threads.c
> +        start = strstr(buffer, "//");
?

2024-01-04 05:33 UTC, VMenshchikov commented
test

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        sPollPush(spoll, newSockets);
accept -> кидаю в очередь №1 -> устанавливаю соединение, пересылаю запрос, и кидаю в структурку с poll -> poll ожидает ответа на запрос -> кидаю в очередь №2(тредпул реализован на вламывании в эту очередь) -> пересылаю ответ и закрываю

не совсем понял про перезапуск цикла тк соединение отправляется в следующую структуру данных, сделанную под poll, логика с точки зрения соединения линейно проходится по очереди, полу и второй очереди

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        sPollPush(spoll, newSockets);
передаю данные дальше по логике программы и поток в новой итерации снова ожидает нового соединения из очереди(можно сделать несколько таких потоков из-за задержек в резолвинге dns и установке соединения)

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        for (rp = result; rp != NULL; rp = rp->ai_next) {
должно закрыться, но я упаду

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +            soc = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
семейство : AF_INET(ipv4), AF_INET6(ipv6), AF_UNSPEC неопределенное/любое
тип: поток и датаграммы
http работает поверх tcp, датаграммы не подойдут

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        start = strstr(buffer, "//");
покажите мне урл больше 4 кб

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        for (rp = result; rp != NULL; rp = rp->ai_next) {
у меня было, что я продолжу пытаться общаться(не обрабатывал случай когда ничего не подошло), исправил(а потом еще раз исправил)

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +            soc = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
можем работать на любой версии ip, используем TCP -> должны использовать потоковый тип

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        start = strstr(buffer, "//");
если урл больше 4кб, то я скинул бы соединение тк не смог бы распарсить урл
если я распарсил урл и сам запрос после этого вышел за рамки 4 кб(с начала), то я бы отправил только кусок запроса

отсутствие // или / я обрабатыввал, других проблем не вижу

2024-01-04 05:59 UTC, VMenshchikov commented on proxy/threads.c
> +        for (rp = result; rp != NULL; rp = rp->ai_next) {
*я бы попытался записать в -1 сокет или в сокет после провального подключения*

2024-01-04 15:24 UTC, k-stolyarov approved these changes
Accepted

2024-04-18 17:32 UTC, merged