threads
VMenshchikov/fit_os_21212 pull request #5
Opened 2023-12-21 20:26 UTC by VMenshchikov

Была проблема как у Вадима(только заметил). Пересоздал

2023-12-24 14:38 UTC, k-stolyarov requested changes

2023-12-24 14:38 UTC, k-stolyarov commented on kernel_threads/kthreads.c
> +        perror("futex_wait");
what do perror and why it is bad idea to check errno without error code check.

2023-12-24 15:14 UTC, VMenshchikov commented on kernel_threads/kthreads.c
> +        perror("futex_wait");
perror выводиз занчение переменной errno, плохая идея почему не знаю(но звучит как плохая идея), предоложу, что она может быть пустой и лишний вывод
я проверяю потому что убедился, что при успехе она заполняется сообщением об успехе

2023-12-24 15:15 UTC, VMenshchikov commented on kernel_threads/kthreads.c
> +        perror("futex_wait");
не проверяю, а вывожу*

2023-12-25 14:08 UTC, k-stolyarov commented on kernel_threads/kthreads.c
> +        perror("futex_wait");
still awaiting for full brief reply )

2023-12-25 14:44 UTC, VMenshchikov commented on kernel_threads/kthreads.c
> +        perror("futex_wait");
обертки над сисколами изменяют переменную errno в случае ошибки и (опционально) в случае успеха, в моем случае они устанавливаются и в случае успеха, но это не гарантированное поведение, UB (errno может быть пустой)
perror выводит состояние errno в std err

2023-12-30 13:25 UTC, k-stolyarov approved these changes
Accepted

2023-12-30 16:09 UTC, merged